name: Check DeployType by MDP
branding:
  icon: truck
  color: red
author: Clark159
description: GitHub Action for Check DeployType


inputs:
  deployHostPaths:
    description: DeployHost Paths
    required: false


runs:
  using: composite
  steps:
  
    - name: Check ChangedFiles
      uses: tj-actions/changed-files@v40
      with:
        files_yaml: |
          hosts:
          ${{ (inputs.deployHostPaths == '' && '- .github/**') || inputs.deployHostPaths }}
          ${{ (inputs.deployHostPaths == '' && '- deploy/**') || '' }}
      id: changed-files
      
    - name: Display Outputs
      shell: bash
      run: |
        echo deployType=${{ steps.changed-files.outputs.hosts_any_changed == 'true' && 'hosts' || 'apps' }}


outputs:
  deployType:
    description: DeployType=[hosts/apps]
    value: ${{ steps.changed-files.outputs.hosts_any_changed == 'true' && 'hosts' || 'apps' }}